# Generated by Django 4.0.4 on 2023-01-17 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('photo', models.ImageField(blank=True, default='dishes/food.jpg', upload_to='dishes')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dishes',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_date', models.DateField(blank=True, default=datetime.date.today)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(db_column='path', upload_to='invoices')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('path', models.ImageField(max_length=255, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfreaderApp.dishes')),
            ],
            options={
                'db_table': 'qr_code',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfreaderApp.invoices')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='invoices',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdfreaderApp.suppliers'),
        ),
        migrations.CreateModel(
            name='DishesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfreaderApp.dishes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfreaderApp.products')),
            ],
            options={
                'db_table': 'dishes_products',
            },
        ),
    ]
