# Generated by Django 4.0.4 on 2023-03-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfreaderApp', '0004_user_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='copy_of',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.SET_NULL, to='pdfreaderApp.dishes'),
            preserve_default='True',
        ),
    ]
