# Generated by Django 4.0.4 on 2023-03-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfreaderApp', '0005_dishes_copy_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='code',
            field=models.CharField(default='7bf28c6610-WXXG2', max_length=50),
        ),
    ]
