# Generated by Django 4.0.4 on 2023-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfreaderApp', '0007_alter_invoices_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
